server:
  port: 8080


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instanceId:${server.port}}
    prefer-ip-address: true
  
logging:
  level:
    com.netflix.discovery: 'OFF'
  