spring:
  application:
    name: HelloClient

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
   
#UserService:
#  ribbon:
#    ReadTimeout: 1000  
#    ConnectTimeout: 1000
#    ServerListRefreshInterval: 1000
#    MaxAutoRetries: 1
#    MaxAutoRetriesNextServer: 3 
#    OkToRetryOnAllOperations: true
